%% Load and Plot 2D Potential Map (YZ Plane)
% 1. Configuration
% Replace this with an actual file generated by your Python script
filename = 'D:\CST Python\EfieldRuns\Results\C0\Potential_C0_222.604.txt'; 
target_x = 0; 
target_y = 0; % Added to define the 1D axis slice

% 2. Import Data
% CST Potential export has 4 columns: X, Y, Z, Potential
data = readmatrix(filename, 'NumHeaderLines', 2);
x_all = data(:,1); 
y_all = data(:,2); 
z_all = data(:,3);
V_all = data(:,4); % Electric Potential in Volts

% 3. AUTO-FIND CLOSEST SLICE & CALC LIMITS
unique_x = unique(x_all);
[~, closest_idx_x] = min(abs(unique_x - target_x));
actual_x = unique_x(closest_idx_x);

% Extract 2D slice data
idx_slice = (x_all == actual_x);
y_slice = y_all(idx_slice);
z_slice = z_all(idx_slice);
V_slice = V_all(idx_slice);

% --- Auto-calculate limits ---
V_min = min(V_slice);
V_max = max(V_slice);

% Handle edge case where field is perfectly uniform (e.g., 0V everywhere)
if V_min == V_max
    V_max = V_min + 1e-3; 
end

V_limit = [V_min, V_max]; 

% 4. Reshape for Plotting
uy = unique(y_slice);
uz = unique(z_slice);
[Y, Z] = meshgrid(uy, uz);
V_grid = griddata(y_slice, z_slice, V_slice, Y, Z);

% 5. Create the 2D Plot
figure(1);
clf;

% Define the contour levels dynamically based on min/max
levels = linspace(V_min, V_max, 20); 
[C, h] = contourf(Z, Y, V_grid, levels);
set(h, 'EdgeColor', 'none'); 
colormap(jet);

% Apply Auto-Limits
clim(V_limit); 
cb = colorbar;
ylabel(cb, 'Electric Potential [V]', 'FontSize', 11, 'FontWeight', 'bold');

% Labels and Styling
xlabel('Z [mm]', 'FontSize', 11);
ylabel('Y [mm]', 'FontSize', 11);
title(sprintf('Potential Map (x = %.2f mm) | Range: [%.1f - %.1f] V', actual_x, V_min, V_max), 'FontSize', 12);
axis tight;
grid on;


%% 1D Axial Potential Plot (Z vs V)
% 1. Find the closest y-coordinate for the central axis
unique_y = unique(y_all);
[~, closest_idx_y] = min(abs(unique_y - target_y));
actual_y = unique_y(closest_idx_y);

% Filter for the central axis (where x and y are closest to targets)
idx_axis = (x_all == actual_x & y_all == actual_y);

% 2. Extract Z coordinates and the Potential
z_axis = z_all(idx_axis);
V_axis = V_all(idx_axis); 

% 3. Sort data (CST data can sometimes be exported out of order)
[z_sorted, sort_idx] = sort(z_axis);
V_sorted = V_axis(sort_idx);

% 4. Create the 1D Plot
figure(2);
clf;
plot(z_sorted, V_sorted, 'r-', 'LineWidth', 2); % Changed to red to distinguish from B-field
grid on;
hold on;

% Styling
xlabel('Axial Position Z [mm]', 'FontSize', 11);
ylabel('Electric Potential [V]', 'FontSize', 11, 'FontWeight', 'bold');
title(sprintf('1D Axial Potential Profile (at x=%.2f, y=%.2f)', actual_x, actual_y), 'FontSize', 12);

% Optional: Add a horizontal line at V=0 for reference
hold on;
yline(0, 'k--', 'HandleVisibility', 'off', 'LineWidth', 1.5); 
axis tight;
hold on;